spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dogtor
    username: root
    password: 1234

  mvc:
    view:
      prefix: /WEB-INF/views/jsp/
      suffix: .jsp
  web:
    resources:
      static-locations: classpath:/static/
  logging:
    level:
      org.springframework.web: DEBUG

jwt:
  secret: "dogtorSecretKey123!@#dogtorSecretKey123!@#dogtorSecretKey123!@#"  # 최소 32바이트 이상의 길이를 가진 키